- platform: template
  switches:
    speicher_fullen:
      turn_on:
        - action: select.select_option
          metadata: {}
          data:
            option: load
          target:
            entity_id: select.multimatic_700_hwcsfmode_sfmode
      turn_off:
        - action: select.select_option
          metadata: {}
          data:
            option: auto
          target:
            entity_id: select.multimatic_700_hwcsfmode_sfmode
      friendly_name: "Speicher füllen"
      unique_id: speicher_fullen
      value_template: "{{ is_state('select.multimatic_700_hwcsfmode_sfmode', 'load') }}"
      icon_template: |
        {% if is_state('select.multimatic_700_hwcsfmode_sfmode', 'load') %}
          mdi:water-boiler
        {% else %}
          mdi:water-boiler-off
        {% endif %}
